name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Correr tests unitarios con cobertura
        run: npm test -- --coverage

      - name: Subir reporte de cobertura
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

      # 🎯 INSTALACIÓN DE PLAYWRIGHT Y DEPENDENCIAS PARA TEST E2E
      - name: Instalar navegadores de Playwright
        run: npx playwright install --with-deps

      # 🧪 TESTS DE ACEPTACIÓN: corre http-server y luego cucumber-js
      - name: Ejecutar tests de aceptación (Cucumber + Playwright)
        run: npx start-server-and-test "http-server -p 8000" http://localhost:8000 "cucumber-js"
